server:
  port: 8888
  
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/repo1010/springcloud-cofigserver-test #(User need to clone content of repository to his
          # own repository and replace uri with his own repository uri
          # also need to provide username and password for his github below)
          # D://workspace/spring/resource/springcloud-cofigserver-test
          #https://github.com/repo1010/springcloud-cofigserver-test
          username: git username
          password: git password
          search-paths:
            - 'level*'
          repos:
            perf:
              pattern:
                - '*/perf/*'
              uri: https://github.com/repo1010/springcloud-configserver-perf-test
              #(User need to clone content of repository to his
               # own repository and replace uri with his own repository uri
               # also need to provide username and password for his github below)
              username: git username
              password: git password
              search-paths:
                - 'level*'  
             